version: '3'
services: 
  jenkins:
    image: localhost:8001/jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    build:
      context: ./linux-jenkins
      dockerfile: Dockerfile
    depends_on:
      - jenkins-slave-gradle
    links:
      - 'jenkins-slave-gradle' 
    container_name: jenkins
    restart: always
  jenkins-slave-gradle:
    image: localhost:8001/jenkins-slave-gradle:latest
    build:
      context: ./jenkins-slave-gradle
      dockerfile: Dockerfile
    container_name: jenkins-slave-gradle
    restart: always
